### ISSUE TITLE
 Converting py args to operator properties:: keyword "export_colors" unrecognized

### ISSUE THREAD

**Issue by IamTheCarl** [kaosat-dev/Blenvy#200]
Hello. I created a simple scene in Blender [provided here as a zip file](https://github.com/user-attachments/files/16356267/map.blend.zip).

When I attempt to use the gltf_auto_export plugin for Blender, I get the following error every time I save:
```
failed to export gltf ! Converting py args to operator properties:: keyword "export_colors" unrecognized
Traceback (most recent call last):
  File "/home/thecarl/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/gltf_auto_export/auto_export/auto_export.py", line 124, in auto_export
    export_main_scene(bpy.data.scenes[scene_name], folder_path, addon_prefs, library_collections)
  File "/home/thecarl/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/gltf_auto_export/auto_export/export_main_scenes.py", line 61, in export_main_scene
    generate_and_export(
  File "/home/thecarl/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/gltf_auto_export/helpers/generate_and_export.py", line 47, in generate_and_export
    raise error
  File "/home/thecarl/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/gltf_auto_export/helpers/generate_and_export.py", line 44, in generate_and_export
    export_gltf(gltf_output_path, export_settings)
  File "/home/thecarl/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/gltf_auto_export/auto_export/export_gltf.py", line 53, in export_gltf
    bpy.ops.export_scene.gltf(**settings)
  File "/app/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties:: keyword "export_colors" unrecognized
```

I have found that if I use your provided example blend files, I do not get this error and the expected gltf is produced.
This is very likely to be user error but it is very unclear what my mistake is. Could someone expand on what's going on here?

Information about my system: [system-info.txt](https://github.com/user-attachments/files/16356300/system-info.txt)
That file does not make it clear that I am running Blender from a [Flatpak](https://flathub.org/apps/org.blender.Blender).

**Comment by chompaa** [comment]
I see that you're using Blender 4.2. I had the same issue, switching to 3.6 fixed it for me. Notably, I had a different (but similar) issue on 3.0, too.

**Comment by jjoshpoland** [comment]
Bumping as I also have this issue.

**Comment by jjoshpoland** [comment]
Updating to say that ARP 3.72.39 seems to have fixed it.
