### ISSUE TITLE
No registry.json generated using the README.md

### ISSUE THREAD

**Issue by hedefalk** [kaosat-dev/Blenvy#246]
I'm trying to walk through the instructions on the quickstart readme https://github.com/kaosat-dev/Blenvy/blob/main/docs/quickstart/README.md, but I get stuck with the a panic on first run and no registry.json is ever generated. Maybe I'm missing something obvious…

```
cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
     Running `./blenvy_test`
2024-09-22T18:46:47.854573Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.6.1 ", kernel: "23.6.0", cpu: "Apple M1", core_count: "8", memory: "16.0 GiB" }
2024-09-22T18:46:47.960631Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-09-22T18:46:48.436161Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
thread 'main' panicked at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blenvy-0.1.0-alpha.1/src/registry/export_types.rs:17:51:
should have created schema file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `blenvy::registry::export_types::export_types`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

No registry.json is generated. I've found this issue which seems related, but seems more related to production builds later faiing and I can't understand what I need to do to progress:

https://github.com/kaosat-dev/Blenvy/issues/214

Running with BACKTRACE:

```
🐟 set -x RUST_BACKTRACE 1; cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/blenvy_test`
2024-09-22T18:49:18.229489Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.6.1 ", kernel: "23.6.0", cpu: "Apple M1", core_count: "8", memory: "16.0 GiB" }
2024-09-22T18:49:18.329121Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-09-22T18:49:18.838957Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
thread 'main' panicked at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blenvy-0.1.0-alpha.1/src/registry/export_types.rs:17:51:
should have created schema file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/04a318787b39732e306faf5ef6dc584990f4f417/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/04a318787b39732e306faf5ef6dc584990f4f417/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/04a318787b39732e306faf5ef6dc584990f4f417/library/core/src/result.rs:1689:5
   3: core::result::Result<T,E>::expect
             at /rustc/04a318787b39732e306faf5ef6dc584990f4f417/library/core/src/result.rs:1059:23
   4: blenvy::registry::export_types::export_types
             at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blenvy-0.1.0-alpha.1/src/registry/export_types.rs:17:18
   5: core::ops::function::FnMut::call_mut
             at /rustc/04a318787b39732e306faf5ef6dc584990f4f417/library/core/src/ops/function.rs:166:5
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/04a318787b39732e306faf5ef6dc584990f4f417/library/core/src/ops/function.rs:294:13
   7: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn() .> Out>>::run::call_inner
             at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/exclusive_function_system.rs:218:21
   8: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn() .> Out>>::run
             at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/exclusive_function_system.rs:221:17
   9: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run::{{closure}}
             at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/exclusive_function_system.rs:111:23
  10: bevy_ecs::world::World::last_change_tick_scope
             at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/world/mod.rs:2215:9
  11: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /Users/viktor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/exclusive_function_system.rs:103:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `blenvy::registry::export_types::export_types`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by hedefalk** [comment]
Never mind me, shit behind the wheels, had put art under assets…
